# Generated by Django 5.2.7 on 2025-10-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='is_coompleted',
            new_name='is_completed',
        ),
    ]
